### ISSUE TITLE
The system cannot find the path specified

### ISSUE THREAD

**Issue by TonioVE** [SteamDatabase/SalienCheat#105]
Hi I get the error "The system cannot find the path specified" after starting the .bat file. What should I do?

Thanks

**Comment by zochris** [comment]
Take a look at #98 
Maybe that helps.

**Comment by blablabla156** [comment]
I got it working after changing and deleting the whole bat file and keeping only this

>
@echo off
start "cheat" "C:\php\php.exe" -f C:\php\SalienCheat\cheat.php
