### ISSUE TITLE
Color fonts were not visible using python in windows 10.

### ISSUE THREAD

**Issue by prueba543210** [SteamDatabase/SalienCheat#107]
I think it's not really a script problem. I put it here for people to see, I'm sorry if it's not the place.
Solved like this:
open regedit
go to [HKEY_CURRENT_USER \ Console]
modify or add if the key is not:
"VirtualTerminalLevel" = dword: 00000001

Sources:
https://github.com/Microsoft/WSL/issues/1173#issuecomment-254250445

**Comment by K4r0qtuYNE5G4qgZ** [comment]
I use Ansicon https://github.com/adoxa/ansicon/releases because Windows CLI doesn't support Ansi.

**Comment by SakhJack** [comment]
use this

$ pip install coloredlogs

**Comment by rossengeorgiev** [comment]
If you are using windows, I suggest using cygwin (mintty) or  cmder or full vm with vagrant & virtualbox or anacodna. cygwin+vagrant+virtualbox is very solid combo. Everything else on windows seems to half assed.
