### ISSUE TITLE
too many EResult 93

### ISSUE THREAD

**Issue by ffxivvillein** [SteamDatabase/SalienCheat#113]
try again after 1~3 sec, then success.

it's my isp problem?

**Comment by nickflash01** [comment]
having same issue

**Comment by Sofiasock** [comment]
No I get this issue as well.

**Comment by Faalagorn** [comment]
Luckily script renews just fine after that second, but that's definitely something to look at, seeing as multiple people have the issue (I have it as well) – can't say for sure but it seems that missing second adds for each rotation, making it tiny bit slower (it adds up).

It doesn't happen always for me, only from time to time though.

**Comment by nickflash01** [comment]
now is too frequent for me......it happens every 5 to 10 mints once or twice

**Comment by Idyoj** [comment]
Same problem here right now, but am really only getting ERseult: 93

**Comment by itsflashpoint** [comment]
same here, I get like 4 - 5 EResult 93 then it does 1 mission and loops back to result 93.

**Comment by ooinovaioo** [comment]
I also get it about every 4-10 minutes on Windows via php.

**Comment by JourneyOver** [comment]
if you guys are running the latest version you can mostly ignore the 93 errors as it resubmits the score.. now if you are getting the 93 error with the resubmit as well then we are trying to see if we can find a fix for that.

**Comment by RageGirl** [comment]
After new update by xpaw still getting this error frequently, don't know why it's happening on my andriod via termux? is it bad or it's fine fine having no influence on xp farming. Any developer?
![whatsapp image 2018-06-25 at 11 34 01 am](https://user-images.githubusercontent.com/40558023/41840520-5c38b100-787f-11e8-9578-80a3ba1d0d13.jpeg)

**Comment by JourneyOver** [comment]
@RageGirl read my message right above yours

**Comment by RageGirl** [comment]
Thanks for explanation @JourneyOver

**Comment by ffxivvillein** [comment]
Thanks :)
