### ISSUE TITLE
XP %age to next level interpretation

### ISSUE THREAD

**Issue by jmbox** [SteamDatabase/SalienCheat#114]
Maybe just me, but I would assume that when you hit a new level, %age to next level would start at zero. Instead it goes to somewhere between 37-75%, because that's how much total XP you have before the next level. 

So currently, you're constantly running from (37-75)-100%, instead of 0-100%. Took me until now to figure this out, wondering how I was so far along in the next level each time...

Mathematically, (new_score - prev_level_score) / (next_level_score - prev_level_score)
[XP Table](https://www.reddit.com/r/Saliens/comments/8t0o1c/xp_table/) from Reddit u/unhi

Perhaps you could display both? Level % and Total % ?

**Comment by Faalagorn** [comment]
I was genuinely thinking to submit the very same issue right now – I mentioned it once in Discord, but it got lost without reply and didn't bring myself to write here since, but I also think that the percentage shown should be from this level to next level and not from 0 to next level.

**Comment by ALEEF02** [comment]
I'll try to implement this and then make a pull request

**Comment by ALEEF02** [comment]
Pull request up
