### ISSUE TITLE
Error 42

### ISSUE THREAD

**Issue by 0wnMe0rDie** [SteamDatabase/SalienCheat#115]
Too lazy to set up a PR.

Lots more 42s are occurring because of the check being after 60 seconds. The decision on zone is made after this check. By the time you submit score (+48), that could have been capped up past the cutoff and therefore you join the zone anyway and then get hit with 42.

Proposal fix is to change the time before selecting planet to something like 90-100 seconds. The latter part (score submit) will still occur after the other 7-9 seconds (if set to 100). With this change, far fewer (none) 42 errors have been observed by multiple people. 

Msg( '   {grey}Waiting 100 seconds before rescanning planets...' );

sleep( 100 );

Thoughts?

**Comment by ALEEF02** [comment]
I will make a PR

**Comment by ALEEF02** [comment]
Done

**Comment by JourneyOver** [comment]
I don't think 42s are ever going to be fully fixed, because even latest changes up to https://github.com/SteamDatabase/SalienCheat/commit/476e7dc57819b16c170c080bb571c95a2b0bf485 still sometimes produce a 42.

**Comment by Sulizab** [comment]
If ETA for picked zone lower than 3-4 min mostly result is 42. Lost time for farm.
