### ISSUE TITLE
Is it possible to send score increase without playing a 2 minute game?

### ISSUE THREAD

**Issue by thomwblair** [SteamDatabase/SalienCheat#119]
- Is it technically possible to send in score increases without playing a round of the game? 
- If so, will Steam care? 
- If so, do they need you to do it kind of slowly, so it doesn't stick out so much to suddenly have a 1,000,000 score increase?
- If so, how slowly?

I don't want to get banned or make people mad. :/

**Comment by Kowiz** [comment]
No
