### ISSUE TITLE
getting this error while using termux on android dosn't happen using windows with php

### ISSUE THREAD

**Issue by RageGirl** [SteamDatabase/SalienCheat#123]
[06:00:09] !! ITerritoryControlMinigameService/ReportScore failed - EResult: 93 - {"response":{}}
[06:00:09] -- EResult 93 means time is out of sync, trying again in 1.298 seconds...
![whatsapp image 2018-06-25 at 11 34 01 am](https://user-images.githubusercontent.com/40558023/41833941-c9a056c6-786b-11e8-9a11-4e3b3b359689.jpeg)

Using saliencheat with Termux on galaxy s6
this error dosent appear on windows but on android it appear After 9-12 minutes.

Any help is appreciated, thanks in advance <3

**Comment by santidaross** [comment]
#113

**Comment by Rawrlex** [comment]
@RageGirl Any way to contact you and share details about setup on Android?

**Comment by RageGirl** [comment]
@Rawrlex u want to use this Script on Android phone?

**Comment by RageGirl** [comment]
@Rawrlex 
To use SalienCheat follow the following steps;

1. Install Termux from Play Store

2. Give Storage Permissions to Termux (Long press the app icon> app info> permissions> Storage)

3. Open Termux

4. Type "apt update" enter

5. Type "apt upgrade" enter

6. Type "apt install termux-api php" enter

7. Type "pkg install git php"

8. Type "git clone https://github.com/SteamDatabase/SalienCheat.git"

9. Type "cd SalienCheat"

10. Type "php cheat.php YOURTOKEN"

**To Update Script as @Xpaw is working very hard to make stable Script**

1. hit ctrl-c (Volume down + C) to stop the script

2. Type "git pull"

3. Type "php cheat.php YOURTOKEN"


I hope this help, this is the best way to use this script power efficiently on android device.

**Comment by Faalagorn** [comment]
Actually, I think these instructions could be added to main readme, you want to make PR @RageGirl ?
