### ISSUE TITLE
Next Level % is still bugged

### ISSUE THREAD

**Issue by GreatOldOne** [SteamDatabase/SalienCheat#127]
`return ( $Data[ 'new_score' ] - $PreviousLevel ) / ( $Data[ 'next_level_score' ] - $PreviousLevel );`

should be

`return ( $Data[ 'new_score' ] - $ScoreTable[ $PreviousLevel ] ) / ( $Data[ 'next_level_score' ] - $ScoreTable[ $PreviousLevel ] );`

in function GetNextLevelProgress.

**Comment by ooinovaioo** [comment]
Which would that edit go in? :octocat:
