### ISSUE TITLE
Warn that the script has been modified

### ISSUE THREAD

**Issue by GreatOldOne** [SteamDatabase/SalienCheat#131]
May I push a PR that informs the user that the script has been modified, but still requires manual update?

What I've here is, while awaiting to report the score, it buffers with https://raw.githubusercontent.com/SteamDatabase/SalienCheat/master/cheat.php and the local php cheat.php and then generate sha1 hashes for both.

Once the report is done, compare both hashes and if !=, reports a newly modified script at the repository.

**Comment by rossengeorgiev** [comment]
Sure. There is an API https://api.github.com/repos/SteamDatabase/SalienCheat/git/trees/master

If could update both script that would be awesome.

**Comment by GreatOldOne** [comment]
Easy enough to implement on both languages. We should only warn the user for the current script running.

**Comment by GreatOldOne** [comment]
Ok. PR for the PHP version made. Tested on my end and all the hashes are correct aswell as the messages.
Will do the Python one once we get the PHP one commited.

**Comment by GreatOldOne** [comment]
Example: https://i.imgur.com/heM22lL.png
