### ISSUE TITLE
Please Update How to Use Method with Android, it work perfectly on Mobile.

### ISSUE THREAD

**Issue by RageGirl** [SteamDatabase/SalienCheat#132]
To use SalienCheat on Android follow the following steps;

Install Termux from Play Store

Give Storage Permissions to Termux (Long press the app icon> app info> permissions> Storage)

Open Termux

Type "apt update" enter

Type "apt upgrade" enter

Type "apt install termux-api php" enter

Type "pkg install git php"

Type "git clone https://github.com/SteamDatabase/SalienCheat.git"

Type "cd SalienCheat"

Type "php cheat.php YOURTOKEN"

To Update Script as @xPaw is working very hard to make stable Script

hit ctrl-c (Volume down + C) to stop the script

Type "git pull"

Type "php cheat.php YOURTOKEN"

I hope this help, this is the best way to use this script power efficiently on android device.

**Comment by Faalagorn** [comment]
Why close this? While I haven't tested this myself and there's a bunch of ways to run it on Android I guess it would be handy to have instructions for common folk wishing to run the script on Android.

I guess I can help making this proper PR if needed unless @RageGirl want to.

**Comment by RageGirl** [comment]
@Faalagorn i tried to share my knowledge with community to help, as it works perfectly fine on Android plus it's power efficient don't why developer close my request. it's indeed handy instead of running full pc whole night for xp farming.

**Comment by RageGirl** [comment]
@Faalagorn it's a request to make it a proper PR, i just wanted to contribute what i know.

One thing more to keep your script running in background 24/7 acquire wake lock either by clicking on the Termux notification or entering the termux-wake-lock command in the Termux terminal interface. This will prevent the device from going into deep sleep, which disconnect itself from WiFi and stop the script.
