### ISSUE TITLE
Script stops 

### ISSUE THREAD

**Issue by Tras** [SteamDatabase/SalienCheat#137]
It simply stops working, even at the first zone without a message and when I click CTRL + C it starts up again giving me something like 
"Waited 167.888 (+0.0000 lag) total seconds before sending score"

If I wait too long, it just gives me:
!! ITerritoryControlMinigameService/ReportScore failed - EResult: 42 - {"response":{}}
EResult 42 means the zone has been captured while you were in it"
Tried re-installing, but I get the same. Yesterday an older script worked fine so it's something new from between like 34~ hours ago to 8~ hours ago. 

When restarting with CTRL + C it sometimes starts working again, but tends to report EResult: 93.

Am I missing something?

**Comment by xPaw** [comment]
Your network is timing out on API calls.

**Comment by rossengeorgiev** [comment]
Connect to WIFI 📶

**Comment by Tras** [comment]
I can't connect to WIFI on this computer and I don't know how to fix my network timing out on API calls, honestly don't even know what that is.

It's rather weird though, because now the script has been running for 10 minutes and works after I restarted it.

**Comment by doonce** [comment]
It does seem to stop sometimes for me as well and I have to ctrl+c. I'm not getting any error message, it just looks stuck.

**Comment by Tras** [comment]
Basically same for me, the error I receive comes after I start it up again with CTRL + C if I wait too long.
