### ISSUE TITLE
Py: memory usage

### ISSUE THREAD

**Issue by smkw33d** [SteamDatabase/SalienCheat#138]
Memory usage keeps increasing. Maybe you can add some GC?

**Comment by DarkMio** [comment]
I head the java GC is pretty good for that, maybe import it

**Comment by rossengeorgiev** [comment]
Oh yeah care to provide more details?

OS, python version, memory usage before, now, etc

**Comment by smkw33d** [comment]
The script is running on a 128M VPS, so don't worry too much about this issue.
OS: Debian 8.11 x64
Python Version: 2.7.9
Memory usage increased from ~20M to ~40M

**Comment by rossengeorgiev** [comment]
I'm getting similar usage. 20MB is not issue nowadays. I guess you can manually GC, but no time to experiment with that. I would be hard to get recent version of py3 on jessie.

**Comment by smkw33d** [comment]
Upgraded VPS, problem solved.

**Comment by rossengeorgiev** [comment]
Pay 2 cheat 🥇
