### ISSUE TITLE
Script update error.

### ISSUE THREAD

**Issue by coxapy** [SteamDatabase/SalienCheat#144]
Latest version of the script says about new version, but there no update on github.

**Comment by xPaw** [comment]
Have you actually updated to last version? 96c49ffc7ba8fe1547713da2b4a5509dcc8ecc40

**Comment by GreatOldOne** [comment]
Been working fine for me. Out of curiosity, try downloading the raw file and see if the problem stops.

**Comment by coxapy** [comment]
Yes, last raw version.

**Comment by GreatOldOne** [comment]
Did you copy and paste or click Save as?

**Comment by Corbian** [comment]
my 2 cents:

The currently used API ( https://api.github.com/repos/SteamDatabase/SalienCheat/git/trees/master ) returns the contents of the repo, and then it's a mess with hashes.
Downloading the file then hashing it is not kind on resources (cpu & net).

There is an interesting API there:
https://api.github.com/repos/SteamDatabase/SalienCheat/commits

The return value is the list of the commits, with the date of the last one in 1st position.
Then it's just a matter of converting the date then comparing it to a reference date : why not the date of __FILE__ ?

Implementing that is beyond my PHP skills ; but maybe:
// download with curl then :
$Data = json_decode( $Data, true );
if ( isset( $Data[ 0 ][ 'commit' ][ 'author' ][ 'date' ] ) )
{
$NewDate = $Data[ 0 ][ 'commit' ][ 'author' ][ 'date' ] ; // need conversion ? it's "2018-06-25T15:22:15Z"
// and so on...

/my 2 cents

**Comment by coxapy** [comment]
Copypaste.. Will try save as.

**Comment by xPaw** [comment]
The link you are describing is what is currently on master.

**Comment by GreatOldOne** [comment]
You need to save as, as you need the correct data sequence when comparing hashes.

**Comment by MikeLund** [comment]
@Corbian how do you think it'd be smarter to download the entire commit log of the repo (currently 112 KB) instead of the current `head` status (3.5 KB)?

But on topic, the copypaste could cause problems, eg file saving with different line-endings will give a different sha1sum.

**Comment by coxapy** [comment]
Save as worked. Thank you.

**Comment by Corbian** [comment]
@MikeLund
Sure, I'm not an expert, but you can add the `since` parameter to limit the size of the answer.
For example, this is returning only 1 commit as the time of writing:
https://api.github.com/repos/SteamDatabase/SalienCheat/commits?since=2018-06-25T15:19:07Z
length = 3905 chars
And when there is no commit to return, the answer is close to zero lengh ; so yes, it's smarter this this way !
