### ISSUE TITLE
Don't d/l full script to check for update

### ISSUE THREAD

**Issue by Corbian** [SteamDatabase/SalienCheat#146]
Like I was saying on #144 ; this API allows to know if there is an update:
https://api.github.com/repos/SteamDatabase/SalienCheat/commits?since=2018-06-25T15:19:07Z

Set the date in the URL ; and the answer is empty is there's no commit after that date.

Also, checking on each loop iteration, that's each `2mins * number_of_users` for GitHub until there's an update.

**Comment by xPaw** [comment]
Fixed.
