### ISSUE TITLE
Prioritization Modes

### ISSUE THREAD

**Issue by snappyapple632** [SteamDatabase/SalienCheat#149]
**Mode 1 - XP Priority:** default mode; prioritizes highest difficulty level available.
**Mode 2 - Capture Priority:** Prioritizes capturing planets; selects the planet with the highest progress level and selects zones within that planet with the highest progress level.

Have the script prompt on startup which mode the user wants to select. If the user does not respond in 10 seconds, Mode 1 is automatically selected.

**Comment by xPaw** [comment]
We have optimized it in such a way that works (for us). Adding modes will just complicate it and more than likely introduce bugs.
