### ISSUE TITLE
PHP error on Windows using cheat.bat

### ISSUE THREAD

**Issue by TheLazyHatGuy** [SteamDatabase/SalienCheat#151]
Anytime I restart the cheat.bat script I get this error https://i.imgur.com/fdfMYJJ.png
until I delete the PHP folder and run the script again

**Comment by GreatOldOne** [comment]
You are probably running the 64-bits binary on a 32-bits OS.

**Comment by pizzahut2** [comment]
Edit the file "downloadphp.ps1". Where it says x64, replace it with x86.
