### ISSUE TITLE
Not being able to only choose zones on a specific planet 

### ISSUE THREAD

**Issue by danielkp1234** [SteamDatabase/SalienCheat#156]
why cant i set it to only choose zones from planet 18 or 19 so if i want a game only from planet 18 it will only use planet 18

**Comment by DarkMio** [comment]
Because you cannot do that.

**Comment by danielkp1234** [comment]
@DarkMio Why you can when do that in the game 
i just want it so it only does planet 18

**Comment by DarkMio** [comment]
Because this is a bot that maximizes the XP you get. If you want to go manually to Planet 18 then you gotta turn off the bot and do it manually.

**Comment by danielkp1234** [comment]
is there any fork of this project that allow me to do that @DarkMio

**Comment by danielkp1234** [comment]
I really want to do it on planet 18 and another planet when it comes
i like does the whole script need to be rewritten to just use another planet ????

**Comment by danielkp1234** [comment]
@xPaw can anybody do that please i really only want a game from planet 22 only can do i just change some lines of code and make it only use planet 22

**Comment by xPaw** [comment]
No.

**Comment by danielkp1234** [comment]
why @xPaw

**Comment by xPaw** [comment]
@DarkMio already said why, stop asking.

**Comment by danielkp1234** [comment]
BUT CANT YOU JUST CHANGE BESTPLANET IN THE CODE AND SET IT TO PLANET 22 @xPaw

**Comment by xPaw** [comment]
Good job, then what do you want from us?

Stop mentioning me.

**Comment by danielkp1234** [comment]
@xPaw my only question is what i need to change it too for planet 22
!

**Comment by DarkMio** [comment]
Easy: Write your own bot.
