### ISSUE TITLE
Want win7 version

### ISSUE THREAD

**Issue by uNMaRsun** [SteamDatabase/SalienCheat#158]
![win7](https://user-images.githubusercontent.com/5930674/41865117-5fd06a86-78d6-11e8-926e-a3f931e1a7af.png)

CMD Win7 ignore all style and colors..

**Comment by uNMaRsun** [comment]
OK. I understood.

**Comment by uNMaRsun** [comment]
Thx for hint. ;)

**Comment by EvgenKo423** [comment]
Or you can use Python one, it now supports Windows as well, including colors.
