### ISSUE TITLE
[question][suggestion]

### ISSUE THREAD

**Issue by Harloq** [SteamDatabase/SalienCheat#162]
![sem titulo](https://user-images.githubusercontent.com/40577852/41869420-50616948-788f-11e8-9e06-ce5f441c407b.jpg)

Is that necessary?
I mean I like it more when the screen was more compact. And that information has no real use.
Just an observation, thanks for the work.

**Comment by xPaw** [comment]
Yes it's useful to see why a zone was chosen.
