### ISSUE TITLE
fails in some cases

### ISSUE THREAD

**Issue by OsweRRR** [SteamDatabase/SalienCheat#165]
![screenshot_1554](https://user-images.githubusercontent.com/23623282/41877103-189b34b2-789e-11e8-809e-8c4e5fe8660d.png)

**Comment by xPaw** [comment]
It still succeeds because it retries.

**Comment by OsweRRR** [comment]
![screenshot_1555](https://user-images.githubusercontent.com/23623282/41877239-90084ea4-789e-11e8-87da-5af69d789004.png)

Okay, then this generates confusions
