### ISSUE TITLE
multiple tokens

### ISSUE THREAD

**Issue by dotechin** [SteamDatabase/SalienCheat#177]
I put SaliensCheat files in php folder but I cannot make my tokens.txt work unless manually copy&paste them. I tried to rename them, check extensions, read closed issues but still I did not make them working. The error message always ask me to check token.txt file. Did I miss some intermediate step? Thanks.

**Comment by dotechin** [comment]
Could I possibly modify cheat.php duplicating the lines and changing 'token.txt' to token1 or token2?

**Comment by xPaw** [comment]
You can pass in token as argument when starting the script, so you don't need token.txt at all.

**Comment by dotechin** [comment]
Man, it is what I was doing already, no worries just asked.
