### ISSUE TITLE
Gets stuck on GetPlanet after empty response

### ISSUE THREAD

**Issue by notderw** [SteamDatabase/SalienCheat#18]
Log:

    Fri, 22 Jun 2018 14:39:32 +0000 - Joined zone 76 - Captured: 93.24% - Difficulty: 1
    Fri, 22 Jun 2018 14:41:32 +0000 - Sending ITerritoryControlMinigameService/ReportScore...
    Fri, 22 Jun 2018 14:41:32 +0000 - {"response":{}}
    Fri, 22 Jun 2018 14:41:32 +0000 - Sending GetPlanet...
    Fri, 22 Jun 2018 14:41:37 +0000 - Sending GetPlanet...
    Fri, 22 Jun 2018 14:41:42 +0000 - Sending GetPlanet...
    Fri, 22 Jun 2018 14:41:48 +0000 - Sending GetPlanet...
    Fri, 22 Jun 2018 14:41:53 +0000 - Sending GetPlanet...
    Fri, 22 Jun 2018 14:41:58 +0000 - Sending GetPlanet...
    Fri, 22 Jun 2018 14:42:03 +0000 - Sending GetPlanet...
    etc etc

Works fine again on restart

**Comment by xPaw** [comment]
You should update the script to latest version.

**Comment by notderw** [comment]
copy that
