### ISSUE TITLE
Documentation / 

### ISSUE THREAD

**Issue by PsyBooty** [SteamDatabase/SalienCheat#180]
Hey guys, first of all, thx for the script it's really good.
Soooo.... I dont know if i should make this here (issue) but i would like to know if is possible to someone make "Documentation" or explain the code a little more, im learning PHP and would love to help in the future...
What i mean is more detailed comments on the lines for advanced stuff.

like wtf is that lol

$LocalScriptHash = sha1( trim( file_get_contents( __FILE__ ) ) );
$RepositoryScriptETag = '';
$RepositoryScriptHash = GetRepositoryScriptHash( $RepositoryScriptETag, $LocalScriptHash );

Thx and sry if its not a thing to ask =/

**Comment by rossengeorgiev** [comment]
FILE is the name of the current file. It gets read and the contents are used to calculate sha1 sum.
The following lines then get the sha1 sum from this repository.
Later the two sums are compared to determine if the script is up to date.

Self documenting code ✨👌🦆

**Comment by PsyBooty** [comment]
> Self documenting code

For some one that just start to see "if`s and wile`s" is not that simple...
But thx...

**Comment by PsyBooty** [comment]
@PredatorIWD yeah, i mean, i have php classes thes month and i would like to learn how this code work, i did some research about the functions that i dont know but the point is why they make that way...
but its okey, im breaking the code piece by piece to see what is what....
But if they put on some lines ` function GetBestPlanetAndZone( &$ZonePaces, $WaitTime ) //This function do this and that , in that way bcus is cool bla bla bla ` would make easer for some one newb to get faster =)


But any way thx u guys!
