### ISSUE TITLE
[PHP] No correct way to end the main loop (eg. to re-launch after update)

### ISSUE THREAD

**Issue by Corbian** [SteamDatabase/SalienCheat#183]
Actual update flow is to terminate the script by hand, then launch it again (which is done by the launcher script).
But this is disallowing to end the script at the right moment : after ReportScore and display of the score, but before anything else.

Since using keyboard input is not really desirable, another way to go can be to use a 'killswitch.txt' file, and to test its presence in the main loop 'while'. This file would then be deleted by the launcher script.

On update, the user would only need to create this 'killswitch.txt' file without worrying about what SalienCheat script is doing. (it still needs to manually replace the updated files)

[Sample 2-lignes patch here](https://github.com/SteamDatabase/SalienCheat/compare/master...Corbian:killswitch)

If this is not too 'complicated' to use, I can make a PR

**Comment by xPaw** [comment]
We're not doing anything related to auto updates.

**Comment by Corbian** [comment]
Ok.
