### ISSUE TITLE
Please add instructions for iPhone users

### ISSUE THREAD

**Issue by rossengeorgiev** [SteamDatabase/SalienCheat#186]
👨‍💻📲🤖📈👍

**Comment by kefirman9000** [comment]
instructions for Nintendo Gamecube users too

**Comment by Sanaki** [comment]
Step 1: Get a new phone....

Though on a serious note, I'd imagine you could run the python script on an android phone with a bit of effort.

**Comment by RageGirl** [comment]
I'm using this Script on my Android Phone with no Issue, Actually i can't burn my PC running whole night for xp farming. Android also do the same job as Windows PHP in a better and efficient way. Even doing Upgrades is as easy as 2 small commands like "git pull" and "php cheat.php YOUR TOKEN".  

so if u have android @rossengeorgiev @kefirman9000  @Sanaki give it a try via Termux, you will love it.

**Comment by hintswen** [comment]
The following steps assume you already have a jailbroken iphone as this is outside the scope of this project.

1. Download curl, PHP, OpenSSH and a SSH app of your choice (iSSH, TouchTerm etc.)
2. Connect to 127.0.0.1 via SSH app
3. Configure php as required (enable curl, set timezone if required)
4. php cheat.php

**Comment by RageGirl** [comment]
@hintswen is there any way to emulate android in iphone? because the method i use in my android doesn't require Rooted device and it's totally safe.

**Comment by yaakov-h** [comment]
You might be able to run the Python script in [Pythonista](http://omz-software.com/pythonista/).
