### ISSUE TITLE
Option to disable color output

### ISSUE THREAD

**Issue by Dilbao** [SteamDatabase/SalienCheat#189]
Output log looks terrible on heroku.
Yes, you can install heroku-cli for colorful logs but I don't want to see colorful logs, I just want to see some readable text.

**Comment by ALEEF02** [comment]
We currently have a PR in to fix it

**Comment by PalmtopTiger** [comment]
I suggest just checking the color support:
https://github.com/composer/xdebug-handler/blob/c602b6e6d08d23c7d89be3b3d203045289714bf7/src/Process.php#L101
This also fixes the problem with cmd.

**Comment by PalmtopTiger** [comment]
@xPaw without checking of ANSICON or ConEmuANSI, the colors will not work in Cmder on Windows 7-8.
