### ISSUE TITLE
Improvement: Run multiple bots in one instance

### ISSUE THREAD

**Issue by Lyrex** [SteamDatabase/SalienCheat#19]
Hey there,

I don't know if you have time for this or not but a cool improvement was if you could provide multiple tokes in `token.txt` and the bot then runs multiple instances of itself, for each line in the file one instance.

**Comment by xPaw** [comment]
PHP scripts supports passing in token directly, like so:
`php cheat.php tokengoeshere`

That should have solved any multi instance problems. It's really not worth the trouble trying to manage multiple accounts within one process. It's easier to just make a script to spin up multiple processes.
