### ISSUE TITLE
Time Zone

### ISSUE THREAD

**Issue by xOrionex** [SteamDatabase/SalienCheat#191]
I keep getting this warning message:

Warning: date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /Users/username/downloads/salien/cheat.php on line 795

I've looked at line 795, and I'm not quite sure what it is asking for. Any ideas?

**Comment by DarkDeviL** [comment]
Set "data.timezone" in your php.ini file to something like, e.g. "UTC", "Europe/London", "Europe/Copenhagen", etc.

Related: #59

**Comment by VladTheImpaller** [comment]
grab timezone from here https://secure.php.net/manual/en/timezones.php

**Comment by xOrionex** [comment]
I'm not seeing a php.ini file. forgive me if I'm just blind.

**Comment by VladTheImpaller** [comment]
it should be inside your php folder

**Comment by xOrionex** [comment]
thats not giving me anything...

**Comment by DarkDeviL** [comment]
Then consult the manual of your operating system and/or PHP, ...

**Comment by xOrionex** [comment]
Okay, thanks for trying

**Comment by mystith** [comment]
Try removing the default, so that it's just php.ini

**Comment by ALEEF02** [comment]
@xOrionex Did you get it to work or do you still need help?

**Comment by Sanaki** [comment]
What version of php are you using (check with php -v) and what operating system? For me on Mint, installed via apt, the php.ini file is located at /etc/php/7.0/cli/php.ini. Knowing which system you're running (and if it was installed manually or via package manager) would help track down where it should be.

**Comment by xOrionex** [comment]
So, I was trying to run it on an iMac, but, I decided to instead pull out my Window surface and try it. It worked instantly on that, so I don't need anymore help. Thanks for all your advice.
