### ISSUE TITLE
Occurring EResult 93 constantly (every 5 minutes)

### ISSUE THREAD

**Issue by zetta-free** [SteamDatabase/SalienCheat#193]
![image](https://user-images.githubusercontent.com/40615353/41944997-37740db2-7981-11e8-917d-4131fa274cbf.png)

The time in saliencheat is 3 hours ahead

How can I fix this?

**Comment by zetta-free** [comment]
Now it's spaming all these problems

![image](https://user-images.githubusercontent.com/40615353/41945433-6758225a-7983-11e8-87bc-0f55f35c0453.png)

**Comment by mystith** [comment]
You're getting these errors because of weekly Steam maintenance. The time being 3 hours ahead doesn't matter, it's just because Steam is in a different timezone. The errors will go away eventually.
