### ISSUE TITLE
getting a lot of Errors on the script ATM 

### ISSUE THREAD

**Issue by Plopinoux** [SteamDatabase/SalienCheat#194]
![cheat error](https://user-images.githubusercontent.com/3912668/41945478-a73e29e4-79ad-11e8-9115-4281edbe3e45.png)

![error 2](https://user-images.githubusercontent.com/3912668/41945495-c1cfbd04-79ad-11e8-8a21-2c1c9cc1c939.png)

**Comment by BlackBeltPanda** [comment]
Same here.

**Comment by rossengeorgiev** [comment]
Its broken on Valve's end. 🤷‍♂️
