### ISSUE TITLE
Script not running (php)

### ISSUE THREAD

**Issue by EricMue** [SteamDatabase/SalienCheat#199]
I followed everything, downloaded and extracted the php script, put the token data into a token.txt file, moved it into the right folder and renamed the php download into php.zip which I also copied into the right folder. Getting me an error along the lines of "system can't find path".
After un-zipping the php.zip manually and again running the bat file I'm now getting this:
![download](https://user-images.githubusercontent.com/18130829/41955400-39d18f1c-79e0-11e8-9552-e5dc45851bec.jpg)

**Comment by VladTheImpaller** [comment]
Update your powershell. Download link here https://www.microsoft.com/en-us/download/details.aspx?id=54616

After you update it, extract cheat files to new folder and run cheat.bat

**Comment by Martan404** [comment]
Try to put the folder directly on the C:\ path

**Comment by EricMue** [comment]
@Martan404 That didn't help
@VladTheImpaller I'm on Win7 Pro. After updating from version 2 to version 5.1 the script now works. Thanks for the info.
