### ISSUE TITLE
Can't see status on heroku

### ISSUE THREAD

**Issue by Danielx64** [SteamDatabase/SalienCheat#206]
So I deployed your app using the heroku option, put my token in and I can't get anything to show up in the logs. How do I check to see if it running?

https://cdn.discordapp.com/attachments/459440871746830338/461473098785619969/unknown.png

**Comment by sicopata7** [comment]
u put workers on and disable dyn?

**Comment by Danielx64** [comment]
Worker is on and what do you mean disable dyn?

**Comment by sicopata7** [comment]
on resource, disabled "web" and token correctly on VAR. on web and with cmd/powersheel works fine so i think your php isnt working

**Comment by JourneyOver** [comment]
if they used the heroku one click, then it's all automatically set up, all they need to do is set the variables @sicopata7

**Comment by Danielx64** [comment]
@JourneyOver, yeah I used the one click for heroku, maybe I should try doing it the dropbox way: https://youtu.be/_77nIqaXPQQ

**Comment by sicopata7** [comment]
I fork the git to initialice and then use git sentences to update when needed :S Srry
