### ISSUE TITLE
Specify next sprint goal for SalienCheat

### ISSUE THREAD

**Issue by DarkMio** [SteamDatabase/SalienCheat#23]
It is currently unacceptable to deploy SalienCheat onto production unless we get sprint goals and development direction (as well as mission statement), to approximate future changes that might need significant devops resources.

Please specify these now. While you're at it, you might want to add a code of conduct to this repo, the objectifying way of your programming of Salien is concering right now.

Thanks and please respond quickly.

**Comment by xPaw** [comment]
k

**Comment by Scrxtchy** [comment]
Plans are to get this on steam direct access

**Comment by DarkMio** [comment]
That is an unacceptable response and we're evaluating other solutions for CI and AWS MQTT to migrate to.

If you can advise us on how we could migrate the local data of SalienCheat please do so.

**Comment by Scrxtchy** [comment]
I propose you use /dev/null as a service for your solution https://devnull-as-a-service.com/
