### ISSUE TITLE
Confirming the max score possible per round

### ISSUE THREAD

**Issue by Faalagorn** [SteamDatabase/SalienCheat#29]
Opening this as issue, hopefully you don't mind, but other than Saliens Discord it's the easier place for me to communicate, but can someone verify if `$Score * 120` (for hards) is the absolute maximum you can get from idling?

I remember that I got 2440 that got through (no error refreshing the game) when playing through browser without any scripts (switching tabs so the monsters don't attack), but maybe it's just my mind failing me. I originally tried chancing it for `+ $Score` before submitting #6 but I got no progress reports assuming it's not working, but maybe it was me that did something wrong, especially as it was a middle of the night.

Others have mentioned of 2400.02 which seems like a float rounding error that might not actually add up, but if it does, then it'll add up on 24/7 idling over time.

**Comment by xPaw** [comment]
I wouldn't trust what the client displays. What matters is what the server accepts. 2400 is max because there's 120 seconds and you get 20 points per second.
