### ISSUE TITLE
bash: 32: No such file or directory

### ISSUE THREAD

**Issue by JilkOwez** [SteamDatabase/SalienCheat#39]
Hello, I am testing out this script and trying to build it with docker, I run the docker start command and it returns:

```
bash: 32: No such file or directory
```

The command I entred was: 

```
docker run -it --init --rm -e TOKEN=<32 character token from gettoken url> steamdb/saliencheat
```

**Comment by VoiDeD** [comment]
Replace `<32 character token from gettoken url>` with your actual token.

**Comment by JilkOwez** [comment]
Yep, I eventully done `docker run --init --rm -e TOKEN=<token.txt character token from gettoken token.txt` & it worked.

**Comment by JilkOwez** [comment]
resolved
