### ISSUE TITLE
not getting score

### ISSUE THREAD

**Issue by nebrassy** [SteamDatabase/SalienCheat#5]
it seems random but common enough to be a real issue, I'm randomly getting

Fri, 22 Jun 2018 02:14:56 +0000 - Sending ITerritoryControlMinigameService/ReportScore...
Fri, 22 Jun 2018 02:14:57 +0000 - {"response":{}}

resulting in no XP

**Comment by NoXPhasma** [comment]
This happens when the Steam servers don't answer. If you run the game in the browser, it's the moment when you get that error message popup.

Depending on the load of the Steam Store, it happens more or less frequent. Nothing you can do about.

**Comment by nebrassy** [comment]
Ah, makes sense, guess nothing to do then.

**Comment by nebrassy** [comment]
But wouldn't it be possible to retry reporting the score instead of just joining a new game to save time?

**Comment by nebrassy** [comment]
Well, I'll leave this open for now, if it works it'd be a great improvement.

**Comment by Scrxtchy** [comment]
It does retry on sending data though

**Comment by xPaw** [comment]
That happens rarely, yeah. I've ran the script through the night, and it worked rather well.

So if you didn't modify the script it should be OK.

**Comment by nebrassy** [comment]
It works great sometimes, other times it's like one game works and the next doesn't, sometimes 3 in a row doesn't work.

**Comment by xPaw** [comment]
Do you also visit the game in browser? That might create issues.

**Comment by nebrassy** [comment]
I'm running it on 3 accounts and it's happening on all of them, I got it open in a browser on one account but it's just idle there, would that affect anything?

**Comment by xPaw** [comment]
I don't know.

**Comment by nebrassy** [comment]
I don't know if you've changed something or the servers are more stable but this is no longer happening
