### ISSUE TITLE
cant leave from planet

### ISSUE THREAD

**Issue by b0Ni** [SteamDatabase/SalienCheat#53]
any idea why? i have multiple accounts working but one of them stuck on "leaving planet"

![screenshot_49](https://user-images.githubusercontent.com/9115234/41809281-8ef2cafa-76f3-11e8-8547-5ef51ee13741.png)

**Comment by xPaw** [comment]
Try stopping the script, try to play the game in browser normally and try again.

Make sure you don't have another script running on this same token.
