### ISSUE TITLE
Docker for Windows?

### ISSUE THREAD

**Issue by RaptorCZ** [SteamDatabase/SalienCheat#65]
Any chance?

**Comment by DarkMio** [comment]
We're sorry, but Docker currently only supports Sun Solaris 10.

**Comment by Scrxtchy** [comment]
switch it to linux containers 😉

**Comment by RaptorCZ** [comment]
@Scrxtchy well, simple, it works, thnx :-)

**Comment by Rzeszow** [comment]
It should work if you create an image yourself.
