### ISSUE TITLE
"Verify your token"

### ISSUE THREAD

**Issue by kevinotto** [SteamDatabase/SalienCheat#66]
I am trying to run this script throught php, I did step-by-step everything but when I am trying to launch it, it says that it did´nt find any token and I need to verify my token but I have already done that.

**Comment by dusekdan** [comment]
Can you please clarify how exactly you put in your token? Maybe show us the command you run **BUT DO NOT PUT YOUR ACTUAL TOKEN HERE**.

**Comment by VladTheImpaller** [comment]
You don't have your token file. Or you saved your token file as token.txt.txt Disable "Hide extensions for known file types" in your windows settings to see exact name of the file. Google how to do it. Token.txt has to be saved in same folder as cheat.php

**Comment by kevinotto** [comment]
I have created text file (.txt) in SalienCheat-master folder (the SalienCheat-master folder is extracted/located to/in php folder). I have copied my token to text file. Here´s my command that I use in

cmd: C:\WINDOWS\system32>cd C:\

C:\>cd php

C:\php>php SalienCheat-master/cheat.php
[19:32:07] Failed to find your token. Verify token.txt

**Comment by VladTheImpaller** [comment]
oh, didn't see it wasn't renamed. 

type
cd c:\php\SalienCheat-master
dir

**Comment by kevinotto** [comment]
@VladTheImpaller 
I did this and this is the result: 
C:\WINDOWS\system32>cd c:\php\SalienCheat-master

c:\php\SalienCheat-master>dir
 Volume in drive C is Windows
 Volume Serial Number is 6205-42C1

 Directory of c:\php\SalienCheat-master

23.06.2018  22:21    <DIR>          .
23.06.2018  22:21    <DIR>          ..
23.06.2018  11:26                50 .dockerignore
23.06.2018  11:26                14 .gitattributes
23.06.2018  11:26                16 .gitignore
23.06.2018  11:26           213 947 cacert.pem
23.06.2018  11:26            16 561 cheat.php
23.06.2018  11:26            17 988 cheat.py
23.06.2018  11:26                81 Dockerfile
23.06.2018  11:26             1 071 LICENSE
23.06.2018  11:26             1 981 README.md
23.06.2018  22:17               228 Token.txt
              10 File(s)        251 937 bytes
               2 Dir(s)  321 453 035 520 bytes free

**Comment by dusekdan** [comment]
It seems that the first uppercase 'T' in your `Token.txt` could be the cause. Try renaming just to `token.txt` (lowercase first letter).

You can do that by running:
`rename Token.txt token.txt`

**Comment by kevinotto** [comment]
@dusekdan  I renamed it but still it didn´t work

**Comment by VladTheImpaller** [comment]
Try saving your token.txt file only with token it it. Go to https://steamcommunity.com/saliengame/gettoken  and copy 32 character long string, you will find it after "token":

**Comment by TheEvilSocks** [comment]
Remove your token file and recreate it lowercase `token.txt`. Windows does not correctly rename capitalization changes.

or another way to use this:

Run the cheat with `php cheat.php YOUR_TOKEN_HERE`, replacing the `YOUR_TOKEN_HERE` with the 32 characters long token you get from the url.

**Comment by kevinotto** [comment]
@VladTheImpaller  Thank you! It worked now :)
