### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function curl_init()

### ISSUE THREAD

**Issue by ChilliHam** [SteamDatabase/SalienCheat#68]
For the life of me, I've tried to follow every step carefully. I've watched the Tut. video and followed the text step by step but I keep encountering the same issue.
```
Fatal error: Uncaught Error: Call to undefined function curl_init() in C:\PHP\SalienCheat\cheat.php:643
Stack trace:
#0 C:\PHP\SalienCheat\cheat.php(399): SendGET('ITerritoryContr...', 'active_only=1&l...')
#1 C:\PHP\SalienCheat\cheat.php(63): GetFirstAvailablePlanet(Array, Array)
#2 {main}
  thrown in C:\PHP\SalienCheat\cheat.php on line 643
```
Any help would be appreciated.

**Comment by xPaw** [comment]
Well you clearly didn't read the readme or watch the video.

**Comment by ChilliHam** [comment]
I removed the simi-colon from ";extension=curl" and renamed the file php.in if that is what you're thinking I missed.

**Comment by DmACKGL** [comment]
@ChilliHam https://youtu.be/Xx6ugBFpIlQ?t=138

**Comment by ChilliHam** [comment]
@DmACKGL I figured out my issue. When saving the file as php.in using the "Save As" option, it creates a new file and you still need to delete the old one for it to work. That was the problem. It wasn't using the new file, still looking at the old one. (used notepad++)
