### ISSUE TITLE
Checks pace of previous zone after it has already switched to a new one

### ISSUE THREAD

**Issue by Ilomantis** [SteamDatabase/SalienCheat#69]
As seen in this picture, the script continues to check the pace of the old zone it switched from and then after that zone has been captured it doesn't output any pace for any zone until it re-scans planets.
![capture](https://user-images.githubusercontent.com/13132504/41813607-7b9031bc-777c-11e8-87f5-fe166bfbbfa2.PNG)

**Comment by xPaw** [comment]
It prints paces over 2% for all zones in your current planet.
