### ISSUE TITLE
EResult 1

### ISSUE THREAD

**Issue by mrskizzex** [SteamDatabase/SalienCheat#7]
Hey, If i use the latest version (switch planets) the script throws 
Fri, 22 Jun 2018 11:05:32 +0200 - Sending ITerritoryControlMinigameService/RepresentClan...
Fri, 22 Jun 2018 11:05:32 +0200 - EResult: 15 - {"response":{}}
Fri, 22 Jun 2018 11:05:32 +0200 - Sending GetPlanets...
Fri, 22 Jun 2018 11:05:33 +0200 - Got planet 5 with 84331 joined players
Fri, 22 Jun 2018 11:05:33 +0200 - Sending ITerritoryControlMinigameService/GetPlayerInfo...
Fri, 22 Jun 2018 11:05:33 +0200 - EResult: 1 - {"response":{"active_planet":"1","time_on_planet":10449,"score":"23770","level":5,"next_level_score":"30000"}}
Fri, 22 Jun 2018 11:05:33 +0200 - Sending ITerritoryControlMinigameService/GetPlayerInfo...
Fri, 22 Jun 2018 11:05:34 +0200 - EResult: 1 - {"response":{"active_planet":"1","time_on_planet":10450,"score":"23770","level":5,"next_level_score":"30000"}}
Fri, 22 Jun 2018 11:05:34 +0200 - Sending ITerritoryControlMinigameService/GetPlayerInfo...
Fri, 22 Jun 2018 11:05:34 +0200 - EResult: 1 - {"response":{"active_planet":"1","time_on_planet":10450,"score":"23770","level":5,"next_level_score":"30000"}}
Fri, 22 Jun 2018 11:05:34 +0200 - Sending ITerritoryControlMinigameService/GetPlayerInfo...

and that message just repeats forever

on old version, the one from yesterday, it works correctly.
Please fix ? :)

**Comment by xPaw** [comment]
You have to join the SteamDB group.
