### ISSUE TITLE
Add a countdown?

### ISSUE THREAD

**Issue by coxapy** [SteamDatabase/SalienCheat#72]
Replace lines 171&173 with:
`	for($i = 0; $i <= $WaitTime; $i++)
	{
		Msg("   {grey}Waiting " . ($WaitTime - $i) . " seconds for the game to end... ", "\r");
		sleep(1);
	}`

**Comment by Ilomantis** [comment]
#44

**Comment by nsilvestri** [comment]
Admittedly a better looking solution than mine, but it still has the same issue of not being able to scroll up because the output updates every second.

**Comment by SlyCedix** [comment]
Did you one better on just a timer. #79

**Comment by coxapy** [comment]
Oh, I use cmder, can scroll with this. Sorry.
