### ISSUE TITLE
Easy Zones Only Behavior Suggestions

### ISSUE THREAD

**Issue by kerzyte** [SteamDatabase/SalienCheat#75]
The same issues with #41 is now occurring when only Easy Zones remain. Perhaps implement the 10 minute check here too?

Furthermore, the prioritization of the planet with the least amount of easy zones is causing this script to flip between planet 6 and 8, I am assuming this is because other scripts are prioritizing planet 6, with no regard to amount of zones remaining. It may benefit everyone to only prioritize the oldest planet when only Easy Zones remain.

**Comment by xPaw** [comment]
I was worried something like that would happen. I could remove the refresh after every round if there are no medium zones and just leave it checking for new planets and refresh every 10 minutes. Do you have any better idea on how to handle this?

**Comment by kerzyte** [comment]
I'll wait for @hintswen to comment after he's done with #86 
#77 is definitely the easy way, but I'm wary of the potential 10 minutes of inefficient leveling. Seems like a rock and a hard place...

**Comment by xPaw** [comment]
Assuming we make sure we only select easy zone if there's no other zone remaining anywhere, then the check for new planets should work just fine.
