### ISSUE TITLE
Latest update kills XP-gain in LOW tiles and error in Score-reports

### ISSUE THREAD

**Issue by xantiema** [SteamDatabase/SalienCheat#76]
ReportScore... EResult: 93 - {"response":{}}

**Comment by gregtham** [comment]
EResult: 93 generally means the score was sent too soon (less than 110 seconds). 
Please make sure you aren't running any additional copies of the script at the same time sending duplicate scores too soon.

**Comment by ChilliHam** [comment]
I'm running into the same issue and I know for a fact that I'm only running one instance of the script.

**Comment by xantiema** [comment]
It did not solve the issue. I even looked up the error on SteamAPI and it was time related. I synched up my timezone in the php.ini file and still no good

**Comment by gregtham** [comment]
Odd. I have several instances running with no problems. I can think of several possible issues:
1. Another script (by another developer), or the actual browser game itself, is running for the same account. 
FIX: Restart your computer to ensure nothing else is running. Immediately after boot, run only the php script and see if the error persists.
2. Multiple scripts are attempting to use the same token. This may have happened if you tried to copy/send the script folder to a friend, and token.txt along with it.
FIX: Ensure you have the right token as detailed in the readme, and restart the script. If you suspect somebody else is using your token, stop all scripts, log into the browser game and note your XP. Close the game and come back 15 minutes later to see if it has increased.
3. Some other unidentified issue with the timer/lag in your network.
FIX: Change line 48. "$WaitTime = 110;" > "$WaitTime = 115;"
This increases the time in between games by 5 seconds, which should give you a larger buffer for something to go wrong but slightly reduces efficiency.

**Comment by xPaw** [comment]
Yeah the script can't do anything about this error.
