### ISSUE TITLE
[Python] Crashed after a while. Restarting crashes instantly again.

### ISSUE THREAD

**Issue by K4r0qtuYNE5G4qgZ** [SteamDatabase/SalienCheat#88]
Crash#1
Zone: 0it [1:17:25, 129852.12it/s]Traceback (most recent call last):
  File "cheat.py", line 470, in <module>
    top_clans = [c['clan_info']['url'] for c in game.planet.get('top_clans', [])][:5]
KeyError: 'url'

Crash#2 (on restarting)
Zone: 0it [1:17:25, 129852.12it/s]Traceback (most recent call last):
  File "cheat.py", line 470, in <module>
    top_clans = [c['clan_info']['url'] for c in game.planet.get('top_clans', [])][:5]
KeyError: 'url'

**Comment by slowthgt** [comment]
can confirm, starting the script causes instant crash

**Comment by dark484** [comment]
As temporary fix you can comment the lines 474,478 and 479 to get it working.

**Comment by bi0logic** [comment]
check https://steamcommunity.com/groups/SteamDB  are you still a member of this group?

I got this same error, and then tried the php script.  The php script was giving me a msg to join
https://steamcommunity.com/groups/SteamDB

I though I was already a member of this group, and after joining the group both scripts are working for me.

**Comment by dark484** [comment]
if you have an old version of the script you need to comment these lines:
        #top_clans = [c['clan_info']['url'] for c in game.planet.get('top_clans', [])][:5]
        #if top_clans:
        #    game.log("^YEL>>^NOR Top clans: %s", ', '.join(top_clans))

**Comment by slowthgt** [comment]
the script meanwhile worked again, my guess is the fault is in the clan list request. Also the traceback has nothing to do with the group check.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
It also happened just on joining the new Planet 13 and probably crashed because there was no top clans at this moment.

**Comment by tobbez** [comment]
No need to speculate. #89 already has the root cause and the proper fix.
