### ISSUE TITLE
Joining other groups?

### ISSUE THREAD

**Issue by Hrxn** [SteamDatabase/SalienCheat#93]
What if someone wants to run this SalienCheat thing while being in another Steam group? 😄

**Comment by South-Paw** [comment]
The idea is you support SteamDB as xPaw put the effort in to write it 👍

**Comment by dusekdan** [comment]
Then this (rude) person, is of course, free to rewrite the cheat in a way that is in another Steam group.

I would not really expect getting an answer to this question. Authors of the code contribute to this repository to strengthen their SteamDB community with scripting and botting newcomers. As being in one particular group does not give you any advantage, I think there is no reason not to support SteamDB group.

**Comment by Hrxn** [comment]
Okay, let's see..
Ah, https://github.com/SteamDatabase/SalienCheat/commit/1ab632d6b5ad8bebfa95434206cfc3360a80360f made some changes in that regard.

Dropping tricks like
```Python
def represent_clan(self, clan, clan_id=int('48''e5''42', 16)):
        return self.spost('ITerritoryControlMinigameService/RepresentClan', {'clanid': clan_id})
```
and
```Python
if ('clan_info' not in game.player_info
                   or game.player_info['clan_info']['accountid'] != 0x48e542):
                    game.represent_clan(0b10010001110010101000010)
```

Really? 😄 
Not sure what this tough obfuscation was trying to achieve.
Come on, this is open source after all. 

Don't get me wrong, I have absolutely nothing against your SteamDB group, quite the contrary, I think SteamDB is a really awesome site and very useful. And you came up with this little helper here, so it's deserved to take the lead and "win" this dainty Steam game here (If there is actually something to win, hell I have no idea).
Well, maybe unless Valve decides to step in and starts to hand out VAC bans or something. Maybe not full blown, real VAC bans, but some form of community ban or a special badge of "honor" 😄

**Comment by xPaw** [comment]
@Hrxn before complaining, look at the latest version.

😄😄😄😄😄😄

**Comment by Hrxn** [comment]
What?

I don't know what you mean. I explicitly linked to the comment that made these changes (`"py: fair play"`).

So I'm not complaining here, good that you made these changes.
Or is there another hidden gem somewhere in there? 😄

**Comment by rossengeorgiev** [comment]
😄😄😄😄😄😄😄😄😄😄😄

**Comment by Hrxn** [comment]
Okay, what's so funny about that now?
