### ISSUE TITLE
The batch file says php is not installed even though it is.

### ISSUE THREAD

**Issue by duttaditya18** [SteamDatabase/SalienCheat#94]
This is due to the fact that the batch file looks for PHP in the current directory.

**Comment by xPaw** [comment]
Yes and it downloads it.

**Comment by duttaditya18** [comment]
No. It should look for PHP in C:\ Drive. I don't expect to put the batch file where PHP is installed.

**Comment by xPaw** [comment]
> It should look for PHP in C:\ Drive.

It shouldn't. The script automatically downloads php and puts it into a subfolder.
