### ISSUE TITLE
Error in cheat.bat

### ISSUE THREAD

**Issue by blablabla156** [SteamDatabase/SalienCheat#98]
I cant run the bat file, it says "the path cannot be reached", something along those lines.

**Comment by dusekdan** [comment]
I am sorry, 'something along those lines' is not good enough. It is always nice when you provide full error log when reporting a bug - please post it here.

In your very case, you are probably missing folder `php` with `php.exe` in directory from which you are running a `cheat.bat` file.

**Comment by blablabla156** [comment]
Of course I'm running the bat file from the SalientCheat folder as you get it from downloading it and of course I have the folder (SalientCheat) inside the php folder on C:\. And the full log is this one: 
"The system cannot find the specif path". It prints it in a loop and i need to Crtl+C to stop.

**Comment by SDMU** [comment]
Sorry to jump into this thread , but can I run multiple powershell/cmd for the same account ?
