### ISSUE TITLE
[Suggestion] Auto-update

### ISSUE THREAD

**Issue by Royalgamer06** [SteamDatabase/SalienCheat#99]
1. Start using versions
2. Save current version of script as variable
3. Create a txt/blank file X in repo with latest version written in it
4. When script is running periodically query github url to raw file X
5. When version is higher than current running script, start updating and restart

**Comment by DarkMio** [comment]
1. No
2. No
3. No
4. No
5. No

**Comment by xPaw** [comment]
Use search.
